### ISSUE TITLE
Criação do Template da Issue

### ISSUE THREAD

**Issue by caiovfernandes** [Requisitos-2019-2-Wire/Wire#1]
Nessa issue deve ser realizada a criação do template da issue, assim como adicionar esse template na nossa wiki. O template tem que ter passo a passo de como criar uma issue.

### Tasks: 
- [x] Adicionar o template da issue na wiki;
- [x] Elaboração do template da issue.

**Comment by lucasfcm9** [comment]
Template de issue finalizado, cumprindo as duas tasks.
