### ISSUE TITLE
Elicitação de Requisitos - Questionário

### ISSUE THREAD

**Issue by caiovfernandes** [Requisitos-2019-2-Wire/Wire#12]
## Descrição da Issue
Desenvolver perguntas com o intuito de elicitar requisitos da aplicação [Wire](https://wire.com/en/) por meio de um questionário. Tais perguntas serão aplicadas a um formulário online via google forms, este formulário será disponibilizado para que a comunidade o responda e forneça informações relevantes à elicitação de requisitos.

### Tasks: 
Produzir perguntas voltadas para a elicitação dos requisitos da aplicação.
- [x] Adicionar perguntas ao google forms.
- [x] Disponibilizar o questionário à comunidade.

**Comment by iurisevero** [comment]
Por enquanto pensei nessas perguntas, caso pense em outras, adiciono ao comentário

• Você já usou o Wire? (S/N)
• Você experimentaria um novo app mensageiro? (0 – 5)
• Você usaria um aplicativo exclusivamente para assuntos relacionados ao ambiente de trabalho/estudo? (0 - 5)
• Você acha necessário um aplicativo de mensagens com maior qualidade de segurança?(0 - 5)
• Você teria como preferência de escolha um aplicativo open source? (0 - 5)
• Você acha necessário reunir ligações de áudio, vídeo, mensagens e troca de arquivos em um só aplicativo? (0 – 5)
• Você confiaria numa cloud externa para guardar seus documentos? (0 - 5)

**Comment by gitgabiru** [comment]
<b>1.</b> Você confiaria em usar um aplicativo Open Source (código aberto)? --inspired by Iuri
<b>2.</b>  Como você classificaria sua atual experiencia com aplicativos de comunicação (ex: whatsapp, telegram...)? (0-5)
<b>3.</b>  Você acha seguro compartilhar informações de trabalho nos atuais aplicativos de comunicação? (S/N)
<b>4.</b>  Os atuais aplicativos de comunicação (individualmente) conseguem suprir suas necessidades de compartilhar mensagens, documentos, reuniões virtuais e etc. (0-5)
<b>5.</b>  Você pagaria por um serviço de comunicação mais seguro para o seu trabalho? Se sim, quanto/mês? (S/N, $/M)

**Comment by sudjoao** [comment]
Achei algumas perguntas bastante viáveis, irei fazer algumas alterações e começar a coloca-las no questionário, sobre a questão das notas de escala 0-5 eu irei modifcar para 1-5 ou 0-4 pois têm estudos que mostram que questionários com escalas que trabalham com um número impar de opções são mais fáceis de responder devido ao fato de que os que utilizam um número par de opções não tem um número no meio para ser utilizado como a opção neutra, no caso de (1, 2, 3, 4 e 5) terias 1 e 2 como negativos 3 como neutro e 4 e 5 como positivos.

**Comment by caiovfernandes** [comment]
Link para o questionário: [](https://forms.gle/61MrzehSRaGk4pwa9)

**Comment by sudjoao** [comment]
Todos os tasks da Issue foram completados, o link do questionário está acima, apenas esperando uma base de dados mais consistente para iniciar as análises.
