### ISSUE TITLE
Criação Rich Picture - Individualmente

### ISSUE THREAD

**Issue by lucasfcm9** [Requisitos-2019-2-Wire/Wire#3]
## Descrição da Issue
Foi definido em grupo após a aula do dia 27/08/2019 que cada integrante faria uma Rich Picture baseado no aplicativo Wire que teremos como base na matéria.

### Tasks: 
Todas as atividades a serem realizadas devem estar elencadas em tópicos e ao serem finalizadas devem receber um check.
- [x] @lucasfcm9
- [x] @gitgabiru 
- [x] @guilherme-mendes 
- [x] @caiovfernandes 
- [x] @iurisevero 
- [x] @sudjoao

**Comment by caiovfernandes** [comment]
[Ativ01CaioViniciusFernandesDeAraujo.pdf](https://github.com/Requisitos-2019-2-Wire/Wire/files/3553506/Ativ01CaioViniciusFernandesDeAraujo.pdf)

**Comment by caiovfernandes** [comment]
<img width="966" alt="Screen Shot 2019-08-28 at 22 38 31" src="https://user-images.githubusercontent.com/42192251/63903648-93265480-c9e4-11e9-93ad-7c49cffabeed.png">

**Comment by gitgabiru** [comment]
![20190828_200823 (1)](https://user-images.githubusercontent.com/26935152/63903730-ebf5ed00-c9e4-11e9-8cfd-7b359fd595f2.jpg)

**Comment by guilherme-mendes** [comment]
@lucasdutraf obrigado pelo feedback!

**Comment by sudjoao** [comment]
![RichPicture1](https://user-images.githubusercontent.com/46005310/64075457-09e67a80-cc8f-11e9-9109-44c89b29e427.png)

**Comment by sudjoao** [comment]
![RichPicturev1](https://user-images.githubusercontent.com/46005310/64075544-18816180-cc90-11e9-901e-6f76a55b17a7.png)

**Comment by lucasfcm9** [comment]
Essa é a minha versão da *RichPicture*:

![Uploading IMG_0645.JPG…](Rich Picture)

**Comment by lucasfcm9** [comment]
Essa é a minha versão da *RichPicture*:

![rich_picture](https://user-images.githubusercontent.com/40740008/64077592-4b375400-cca8-11e9-87e8-03c3bda9ec9c.jpg)

**Comment by lucasfcm9** [comment]
Issue finalizada! Todos os integrantes do grupo já fizeram suas respectivas Rich Pictures.
